### ISSUE TITLE
How to setup on tree structure defaults working directory?

### ISSUE THREAD

**Issue by daniel-codebrick** [nielsvaneck/render-md-mermaid#3]
My repository structure is like below:
- __parent__
   - __.github__/__workflows__\render-md-mermaid.yml
   - __child1__ <--- just for this specific child1 folder
      - __images__
          - __child1_child__
              - README.md <---
          - README.md  <---
   - __child2__
          -  README.md
   - ...
   - README.md
```
...
on: 
  push:
    paths:
      - child1/**
jobs:
  render-md-mermaid:
    runs-on: ubuntu-latest
    defaults:
      run:
         working-directory: ./child1 # not working

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Render images for every Mermaid diagram in all Markdown files (*.md) in the repo
        uses: nielsvaneck/render-md-mermaid@v1

      - name: Commit rendered png and svg files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          repository: ./child1/images
          commit_message: automatically rendered mermaid diagrams

```

Is there a solution to have a specific working directory with args?
I tried to clone your git repository and change shell find script in 'render-md-mermaid.mk'.
The action works successful but didn't create png and svg.
